[language_name]
'en' = 'English'
'fa' = 'Persian'
'fr' = 'French'
'de' = 'German'
'es' = 'Spanish'
'it' = 'Italian'
'ja' = 'Japanese'
'ko' = 'Korean'
'pt' = 'Portuguese'
'ru' = 'Russian'
'zh' = 'Chinese'
'ar' = 'Arabic'
'hi' = 'Hindi'
'bn' = 'Bengali'
'tr' = 'Turkish'
'vi' = 'Vietnamese'
'th' = 'Thai'
'pl' = 'Polish'
'uk' = 'Ukrainian'
